#]==========================[ Displays ]============================[#

# Primary (Right)
monitor = HDMI-A-1, 1920x1080@144, 1920x0, 1

# Secondary (Left)
monitor = HDMI-A-2, 1920x1080@60, 0x0, 1

#]=========================[ Workspaces ]===========================[#

workspace=1,monitor:HDMI-A-2
workspace=2,monitor:HDMI-A-2
workspace=3,monitor:HDMI-A-2
workspace=4,monitor:HDMI-A-2
workspace=5,monitor:HDMI-A-1,default:true
workspace=6,monitor:HDMI-A-1
workspace=7,monitor:HDMI-A-1
workspace=8,monitor:HDMI-A-1
workspace=9,monitor:HDMI-A-1
workspace=10,monitor:HDMI-A-1

#]======================[ Hyprland Configs ]========================[#

input {
	sensitivity = -0.60
	touchdevice {
		output = HDMI-A-2
		transform = 0
	}
}
